name: Static type check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/*.py'

jobs:
  mypy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Install mypy
        run: pip install mypy
      - name: Type check
        run: mypy src --config-file mypy.ini -v
