name: Unit tests
  
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/*.py'
      - 'test/*.py'
  
jobs:  
  build:  
    runs-on: ubuntu-latest
  
    steps:  
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies  
        run: pip install -r test/requirements.txt
      - name: Unit tests 
        uses: pavelzw/pytest-action@v2
        with:
          emoji: false
          job-summary: false
          click-to-expand: true
